categories:
  maximum: 30
  limit: 5
show_limit:
  show_5: 5
  show_10: 10
  show_15: 15
  show_20: 20
  show_30: 30
  show_50: 50
product:
  featured: 12
  limit: 10
  validates:
    price_maximum: 8
ratings:
  average: 0
order_details:
  quantity:
    default: 1
